<a href="https://colab.research.google.com/github/geethikasri-sirikonda24/MDS_LAB/blob/main/MDS_WEEK_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

# Task 1: Create a 4 x 4 matrix and add values 4,5,6 above the parent diagonal.
print("Task 1: Creating a 4x4 matrix and adding values above the parent diagonal")
matrix_4x4 = np.zeros((4, 4), dtype=int)

# Assigning values 4,5,6 to the elements immediately above the main diagonal
matrix_4x4[0, 1] = 4
matrix_4x4[1, 2] = 5
matrix_4x4[2, 3] = 6

print("4x4 Matrix with values above parent diagonal:\n", matrix_4x4)
print("\n" + "-"*30 + "\n")

# Task 2: Given a Numpy array arr = np.arange(11), negate all the elements between 6 and 10.
print("Task 2: Negating elements between 6 and 10 in a Numpy array")
arr_negate = np.arange(11)
print("Original array:\n", arr_negate)

# Negate elements strictly between 6 and 10 (i.e., 7, 8, 9)
arr_negate[(arr_negate > 6) & (arr_negate < 10)] *= -1

print("Array after negating elements between 6 and 10:\n", arr_negate)
print("\n" + "-"*30 + "\n")

# Task 3: Given a matrix mat and an array arr, for each row of the matrix if elements of Column 1 are equal to the corresponding element of the array, then print the corresponding value of Column 2 of the matrix.
print("Task 3: Conditional printing based on matrix and array comparison")
mat = np.array([['abc','A'],['def','B'],['ghi','C'],['jkl','D']])
arr = np.array(['abc','dfe','ghi','kjl'])

print("Given matrix 'mat':\n", mat)
print("Given array 'arr':\n", arr)
print("Matching values from Column 2:\n")

for i in range(len(mat)):
    if mat[i, 0] == arr[i]:
        print(mat[i, 1])


Task 1: Creating a 4x4 matrix and adding values above the parent diagonal
4x4 Matrix with values above parent diagonal:
 [[0 4 0 0]
 [0 0 5 0]
 [0 0 0 6]
 [0 0 0 0]]

------------------------------

Task 2: Negating elements between 6 and 10 in a Numpy array
Original array:
 [ 0  1  2  3  4  5  6  7  8  9 10]
Array after negating elements between 6 and 10:
 [ 0  1  2  3  4  5  6 -7 -8 -9 10]

------------------------------

Task 3: Conditional printing based on matrix and array comparison
Given matrix 'mat':
 [['abc' 'A']
 ['def' 'B']
 ['ghi' 'C']
 ['jkl' 'D']]
Given array 'arr':
 ['abc' 'dfe' 'ghi' 'kjl']
Matching values from Column 2:

A
C


In [4]:
import numpy as np

mat = np.array([['abc','A'],['def','B'],['ghi','C'],['jkl','D']])
arr = np.array(['abc','dfe','ghi','kjl'])

# Loop through each row of the matrix
for i in range(len(mat)):
    # Check if the element in Column 1 of the matrix matches the corresponding element in the array
    if mat[i, 0] == arr[i]:
        # If they match, print the corresponding value from Column 2 of the matrix
        print(mat[i, 1])


A
C


In [5]:
import numpy as np

mat = np.array([[1,21,3],[5,4,2],[56,12,4]])

print("Original matrix:\n", mat)

# Get the indices that would sort the second column (index 1)
sorted_indices = mat[:, 1].argsort()

# Use these indices to sort the entire matrix
sorted_mat = mat[sorted_indices]

print("\nMatrix sorted by second column:\n", sorted_mat)


Original matrix:
 [[ 1 21  3]
 [ 5  4  2]
 [56 12  4]]

Matrix sorted by second column:
 [[ 5  4  2]
 [56 12  4]
 [ 1 21  3]]


In [6]:
import numpy as np

arr = np.array([90, 14, 24, 13, 13, 590, 0, 45, 16, 50])

print("Original array:", arr)

# Sort the array in descending order and take the first 4 elements
top_4_max_values = np.sort(arr)[::-1][:4]

print("Top 4 maximum values:", top_4_max_values)


Original array: [ 90  14  24  13  13 590   0  45  16  50]
Top 4 maximum values: [590  90  50  45]


In [7]:
import numpy as np

arr = np.array([10,55,22,3,6,44,9,54])
nearest_to = 50

print("Original array:", arr)
print("Number to find nearest to:", nearest_to)

# Calculate the absolute difference between each element and the target number
differences = np.abs(arr - nearest_to)

# Find the index of the minimum difference
nearest_index = np.argmin(differences)

# Get the nearest number from the array using the index
nearest_number = arr[nearest_index]

print("The nearest number in the array is:", nearest_number)


Original array: [10 55 22  3  6 44  9 54]
Number to find nearest to: 50
The nearest number in the array is: 54


In [9]:
import numpy as np

# Original array for demonstrations
base_arr = np.arange(1, 10).reshape(3, 3)
print("Original Array:\n", base_arr)
print("\n" + "-"*30 + "\n")

# --- 1. Indexing ---
print("1. Indexing:")
# Access a single element (row 0, column 1)
print("Element at (0, 1):", base_arr[0, 1])
# Access an entire row
print("First row:", base_arr[0, :])
# Access an entire column
print("Second column:", base_arr[:, 1])
print("\n" + "-"*30 + "\n")

# --- 2. Slicing ---
print("2. Slicing:")
# Slice a sub-array (rows 0-1, columns 1-2)
sub_array = base_arr[0:2, 1:3]
print("Sliced sub-array (rows 0-1, cols 1-2):\n", sub_array)
# Slice from start to specific index
print("First two rows:\n", base_arr[:2, :])
print("\n" + "-"*30 + "\n")

# --- 3. Reshaping ---
print("3. Reshaping:")
# Reshape to a 1D array
reshaped_1d = base_arr.reshape(-1)
print("Reshaped to 1D:\n", reshaped_1d)
# Reshape to 9x1 column vector
reshaped_col = base_arr.reshape(9, 1)
print("Reshaped to 9x1:\n", reshaped_col)
print("\n" + "-"*30 + "\n")

# --- 4. Joining ---
print("4. Joining:")
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print("Array 1:\n", arr1)
print("Array 2:\n", arr2)

# Join vertically (stack rows)
joined_v = np.vstack((arr1, arr2))
print("Joined Vertically (vstack):\n", joined_v)

# Join horizontally (stack columns)
joined_h = np.hstack((arr1, arr2))
print("Joined Horizontally (hstack):\n", joined_h)
print("\n" + "-"*30 + "\n")

# --- 5. Splitting ---
print("5. Splitting:")
large_arr = np.arange(16).reshape(4, 4)
print("Large array for splitting:\n", large_arr)

# Split horizontally into 2 equal parts
split_h1, split_h2 = np.hsplit(large_arr, 2)
print("Split Horizontally Part 1:\n", split_h1)
print("Split Horizontally Part 2:\n", split_h2)

# Split vertically into 2 equal parts
split_v1, split_v2 = np.vsplit(large_arr, 2)
print("Split Vertically Part 1:\n", split_v1)
print("Split Vertically Part 2:\n", split_v2)


Original Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

------------------------------

1. Indexing:
Element at (0, 1): 2
First row: [1 2 3]
Second column: [2 5 8]

------------------------------

2. Slicing:
Sliced sub-array (rows 0-1, cols 1-2):
 [[2 3]
 [5 6]]
First two rows:
 [[1 2 3]
 [4 5 6]]

------------------------------

3. Reshaping:
Reshaped to 1D:
 [1 2 3 4 5 6 7 8 9]
Reshaped to 9x1:
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]

------------------------------

4. Joining:
Array 1:
 [[1 2]
 [3 4]]
Array 2:
 [[5 6]
 [7 8]]
Joined Vertically (vstack):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Joined Horizontally (hstack):
 [[1 2 5 6]
 [3 4 7 8]]

------------------------------

5. Splitting:
Large array for splitting:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Split Horizontally Part 1:
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
Split Horizontally Part 2:
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
Split Vertically Part 1:
 [[0 1 2 3]
 [4 5 6 7]]
Split Vertically Part 2:
 [[ 8  9 10 11]

In [10]:
import numpy as np

# --- Universal Functions (Ufuncs) ---
print("--- Universal Functions (Ufuncs) ---")

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([5, 4, 3, 2, 1])

print("Array 1:", arr1)
print("Array 2:", arr2)

# Element-wise addition
print("Addition (arr1 + arr2):", np.add(arr1, arr2))
# Or simply:
# print("Addition (arr1 + arr2):", arr1 + arr2)

# Element-wise multiplication
print("Multiplication (arr1 * arr2):", np.multiply(arr1, arr2))
# Or simply:
# print("Multiplication (arr1 * arr2):", arr1 * arr2)

# Element-wise square root
print("Square root of arr1:", np.sqrt(arr1))

# Element-wise exponential
print("Exponential of arr1 (e^x):", np.exp(arr1))

# Trigonometric functions
angles = np.array([0, np.pi/2, np.pi])
print("Angles (radians):", angles)
print("Sine of angles:", np.sin(angles))
print("Cosine of angles:", np.cos(angles))

print("\n" + "-"*30 + "\n")

# --- Mathematical Methods (Aggregation and Reductions) ---
print("--- Mathematical Methods (Aggregation and Reductions) ---")

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Matrix:\n", matrix)

# Sum of all elements
print("Sum of all elements:", np.sum(matrix))

# Sum along columns (axis=0)
print("Sum along columns (axis=0):", np.sum(matrix, axis=0))

# Sum along rows (axis=1)
print("Sum along rows (axis=1):", np.sum(matrix, axis=1))

# Mean of all elements
print("Mean of all elements:", np.mean(matrix))

# Maximum element
print("Maximum element:", np.max(matrix))

# Minimum element
print("Minimum element:", np.min(matrix))

# Standard deviation
print("Standard deviation:", np.std(matrix))


--- Universal Functions (Ufuncs) ---
Array 1: [1 2 3 4 5]
Array 2: [5 4 3 2 1]
Addition (arr1 + arr2): [6 6 6 6 6]
Multiplication (arr1 * arr2): [5 8 9 8 5]
Square root of arr1: [1.         1.41421356 1.73205081 2.         2.23606798]
Exponential of arr1 (e^x): [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Angles (radians): [0.         1.57079633 3.14159265]
Sine of angles: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Cosine of angles: [ 1.000000e+00  6.123234e-17 -1.000000e+00]

------------------------------

--- Mathematical Methods (Aggregation and Reductions) ---
Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum of all elements: 45
Sum along columns (axis=0): [12 15 18]
Sum along rows (axis=1): [ 6 15 24]
Mean of all elements: 5.0
Maximum element: 9
Minimum element: 1
Standard deviation: 2.581988897471611
