<a href="https://colab.research.google.com/github/geethikasri-sirikonda24/MDS_LAB/blob/main/MDS_Week_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install numpy

In [2]:
import numpy as np
print(np.__version__)

2.0.2


In [133]:
import time
import numpy as np

# Define the size of the arrays/lists
size = 1000000

# --- Python List Performance ---
start_time = time.time()
python_list_a = [i for i in range(size)]
python_list_b = [i for i in range(size)]
python_list_sum = [a + b for a, b in zip(python_list_a, python_list_b)]
end_time = time.time()
python_list_time = end_time - start_time
print(f"Time taken for Python list: {python_list_time:.6f} seconds")

# --- NumPy Array Performance ---
start_time = time.time()
numpy_array_a = np.arange(size)
numpy_array_b = np.arange(size)
numpy_array_sum = numpy_array_a + numpy_array_b
end_time = time.time()
numpy_array_time = end_time - start_time
print(f"Time taken for NumPy array: {numpy_array_time:.6f} seconds")

print(f"\nNumPy is approximately {python_list_time / numpy_array_time:.2f} times faster for this operation.")

Time taken for Python list: 0.134435 seconds
Time taken for NumPy array: 0.008623 seconds

NumPy is approximately 15.59 times faster for this operation.


### Memory Comparison: Python Lists vs. NumPy Arrays

Let's compare the memory consumption for Python lists and NumPy arrays for similar data sizes.

In [130]:
import sys

# Assuming 'size' is already defined from the previous cell

# --- Python List Memory Usage ---
python_list = [i for i in range(size)]
# For a Python list, we need to consider the size of the list object itself
# plus the size of each element within the list.
# sys.getsizeof(list_obj) gives the size of the list object, not its contents.
# For integers, sys.getsizeof(0) gives the base size of an int object.
# python_list_memory = sys.getsizeof(python_list) + sum(sys.getsizeof(i) for i in python_list[:1000]) * (size // 1000) # Estimate for large list
# A more accurate estimation for memory for a list of integers would be:
# python_list_memory = sys.getsizeof(python_list) # Size of the list structure
# python_list_memory += sum(sys.getsizeof(x) for x in python_list) # Size of individual elements (can be very slow for large lists)
# Let's use a more practical approximation for demonstration:
python_list_memory_approx = sys.getsizeof(python_list) + size * sys.getsizeof(python_list[0]) # List object + average size of elements

print(f"Memory taken for Python list (approximate): {python_list_memory_approx / (1024*1024):.4f} MB")

# --- NumPy Array Memory Usage ---
numpy_array = np.arange(size)
# NumPy arrays store data contiguously and efficiently.
# nbytes gives the total bytes consumed by the array's data.
numpy_array_memory = numpy_array.nbytes
print(f"Memory taken for NumPy array: {numpy_array_memory / (1024*1024):.4f} MB")

print(f"\nNumPy array uses approximately {python_list_memory_approx / numpy_array_memory:.2f} times more memory than a Python list for this operation.")

Memory taken for Python list (approximate): 34.7602 MB
Memory taken for NumPy array: 7.6294 MB

NumPy array uses approximately 4.56 times more memory than a Python list for this operation.


In [101]:
list = [111, 2, 3, 4, 5]

In [11]:
print(type(list))


<class 'list'>


In [102]:
a1 = np.array(list)
print(a1)

[111   2   3   4   5]


In [104]:
import numpy as np

# Create a 1D array with numbers from 1 to 100
array_1_to_100 = np.arange(1, 101)

# Print the array
print(array_1_to_100)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [18]:
a1.dtype

dtype('int64')

In [19]:
a1.dtype.name

'int64'

In [107]:
a1.size

5

In [108]:
a1.shape

(5,)

In [25]:
a1.nbytes

40

In [105]:
tuple = (111,2,3,4,5)
type(tuple)

tuple

In [109]:
tuple2 = (1,)
type(tuple2)

tuple

In [106]:
a2 = np.array(tuple)
print(a2)

[111   2   3   4   5]


In [31]:
a2.size

5

In [32]:
a2.shape

(5,)

In [111]:
list = [[111,2], [3,4]]
matrix = np.array(list)

In [112]:
print(matrix)

[[111   2]
 [  3   4]]


In [35]:
matrix.ndim

2

In [36]:
matrix.shape

(2, 2)

In [37]:
matrix.size

4

In [40]:
matrix.nbytes

32

In [113]:
matrix.flatten()

array([111,   2,   3,   4])

In [42]:
matrix.ravel

<function ndarray.ravel>

In [114]:
matrix.ravel()

array([111,   2,   3,   4])

In [115]:
arr4 = np.array([111,2,3,4])

In [116]:
print(arr4)

[111   2   3   4]


In [117]:
arr5 = np.array([[111,2], [3,4]])

In [118]:
print(arr5)

[[111   2]
 [  3   4]]


In [120]:
arr6 = np.matrix([[111,2], [3,4], [5,6]])
print(arr6)

[[111   2]
 [  3   4]
 [  5   6]]


In [125]:
arr6 = np.arange(1, 100)

In [126]:
print(arr6)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


In [59]:
import numpy as np

# Create a 1D array with numbers from 1 to 100
array_1_to_100 = np.arange(1, 101)

# Print the array
print(array_1_to_100)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [60]:
np.arange(0,100,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [61]:
np.arange(100)

array([], dtype=int64)

In [62]:
import numpy as np

# Create a 1D array with even numbers from 1 to 100 (inclusive)
# We start from 2, as it's the first even number, and go up to 101 (exclusive) with a step of 2
even_numbers_array = np.arange(2, 101, 2)

# Print the array
print(even_numbers_array)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [63]:
matrix2 = np.arange(0, 10)

In [64]:
print(matrix2)

[0 1 2 3 4 5 6 7 8 9]


In [65]:
import numpy as np

matrix2 = np.arange(0, 10)
print("Original matrix2:", matrix2)

# Reshape to 2x5
matrix_2x5 = matrix2.reshape(2, 5)
print("\nReshaped to 2x5:\n", matrix_2x5)

# Reshape to 5x2
matrix_5x2 = matrix2.reshape(5, 2)
print("\nReshaped to 5x2:\n", matrix_5x2)

Original matrix2: [0 1 2 3 4 5 6 7 8 9]

Reshaped to 2x5:
 [[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped to 5x2:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [68]:
import numpy as np

# Create a 4x4 matrix with all elements as 0
zero_matrix = np.zeros((4, 4))

# Print the matrix
print(zero_matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [71]:
a = np.zeros((3,3),dtype='int')
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [72]:
a.dtype.name

'int64'

In [78]:
b = np.ones((3,3), dtype='int')
print(b)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [127]:
c = np.full((3,3), 111)
print(c)

[[111 111 111]
 [111 111 111]
 [111 111 111]]


In [98]:
d = np.eye((3), dtype='int')
print(d)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [83]:
e = np.linspace(0,1,5)
print(e)

[0.   0.25 0.5  0.75 1.  ]


In [88]:
import random

In [90]:
np.random.random((3, 3))

array([[0.43278138, 0.03055232, 0.68566164],
       [0.03772239, 0.40175758, 0.51309008],
       [0.71156037, 0.95897059, 0.02662816]])

In [91]:
matrix2 = np.arange(0, 10)


In [128]:
arr1 = np.arange(1, 10)
print(arr1)

[1 2 3 4 5 6 7 8 9]


In [ ]:
# Set element at index 1 to 111
arr1[1] = 111

# Set element at index 3 to 333
arr1[3] = 333

# Print the modified array
print(arr1)

In [93]:
arr1 = np.arange(1,10)
print(arr1)

[1 2 3 4 5 6 7 8 9]


In [95]:
arr1.min()

np.int64(1)

In [97]:
arr1.max()

np.int64(9)

In [129]:
arr1[0] = 111
print(arr1)

[111   2   3   4   5   6   7   8   9]
