<a href="https://colab.research.google.com/github/geethikasri-sirikonda24/MDS_LAB/blob/main/MDS_WEEK_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import numpy as np

# Initialize a base array for demonstrations
base_arr = np.arange(1, 10).reshape(3, 3)
print("Original Array (base_arr):\n", base_arr)

Original Array (base_arr):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


## Indexing NumPy Arrays - Simple Example

In [23]:
arr = np.array([10, 20, 30, 40, 50])
print("Original array:", arr)
print("Element at index 0:", arr[0])
print("Element at index 3:", arr[3])

Original array: [10 20 30 40 50]
Element at index 0: 10
Element at index 3: 40


## Slicing NumPy Arrays - Simple Example

In [24]:
arr = np.array([10, 20, 30, 40, 50, 60])
print("Original array:", arr)
print("Slice from index 1 to 4 (exclusive):", arr[1:4])
print("Slice from beginning to index 3 (exclusive):", arr[:3])
print("Slice from index 2 to end:", arr[2:])

Original array: [10 20 30 40 50 60]
Slice from index 1 to 4 (exclusive): [20 30 40]
Slice from beginning to index 3 (exclusive): [10 20 30]
Slice from index 2 to end: [30 40 50 60]


## Reshaping NumPy Arrays - Simple Example

In [25]:
arr_1d = np.array([1, 2, 3, 4, 5, 6])
print("Original 1D array:\n", arr_1d)

arr_2d = arr_1d.reshape(2, 3)
print("Reshaped to 2x3 array:\n", arr_2d)

arr_col = arr_1d.reshape(-1, 1)
print("Reshaped to column vector:\n", arr_col)

Original 1D array:
 [1 2 3 4 5 6]
Reshaped to 2x3 array:
 [[1 2 3]
 [4 5 6]]
Reshaped to column vector:
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


## Joining NumPy Arrays - Simple Example

In [26]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Join horizontally (concatenation along axis 0 for 1D arrays)
joined_arr_h = np.hstack((arr1, arr2))
print("Joined horizontally (hstack):", joined_arr_h)

# If they were 2D, vstack would join vertically
arr_a_2d = np.array([[1], [2]])
arr_b_2d = np.array([[3], [4]])
joined_arr_v = np.vstack((arr_a_2d, arr_b_2d))
print("Joined vertically (vstack for 2D arrays):\n", joined_arr_v)

Joined horizontally (hstack): [1 2 3 4 5 6]
Joined vertically (vstack for 2D arrays):
 [[1]
 [2]
 [3]
 [4]]


## Splitting NumPy Arrays - Simple Example

In [27]:
arr = np.array([10, 20, 30, 40, 50, 60])
print("Original array:", arr)

split_arr = np.split(arr, 3) # Split into 3 equal parts
print("Split array into 3 parts:", split_arr)

matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("\nOriginal 2D array:\n", matrix)
split_rows = np.vsplit(matrix, 2) # Split into 2 rows
print("Split 2D array by rows (vsplit):\n", split_rows)

Original array: [10 20 30 40 50 60]
Split array into 3 parts: [array([10, 20]), array([30, 40]), array([50, 60])]

Original 2D array:
 [[1 2 3]
 [4 5 6]]
Split 2D array by rows (vsplit):
 [array([[1, 2, 3]]), array([[4, 5, 6]])]


## Indexing 1D NumPy Arrays (More Examples)

In [28]:
arr_1d_idx = np.array([100, 101, 102, 103, 104])
print("1D Array for Indexing:", arr_1d_idx)
print("Element at index 0:", arr_1d_idx[0])
print("Last element (negative indexing):", arr_1d_idx[-1])
print("Elements at indices 1 and 3:", arr_1d_idx[[1, 3]]) # Fancy indexing

1D Array for Indexing: [100 101 102 103 104]
Element at index 0: 100
Last element (negative indexing): 104
Elements at indices 1 and 3: [101 103]


## Indexing 2D NumPy Arrays (More Examples)

In [29]:
arr_2d_idx = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("2D Array for Indexing:\n", arr_2d_idx)
print("Element at row 0, col 0:", arr_2d_idx[0, 0])
print("Element at row 1, col 2:", arr_2d_idx[1, 2])
print("First row:", arr_2d_idx[0])
print("Last column:", arr_2d_idx[:, -1])

2D Array for Indexing:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Element at row 0, col 0: 10
Element at row 1, col 2: 60
First row: [10 20 30]
Last column: [30 60 90]


## Slicing 1D NumPy Arrays (More Examples)

In [30]:
arr_1d_slice = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print("1D Array for Slicing:", arr_1d_slice)
print("Elements from index 2 to 5 (exclusive):", arr_1d_slice[2:5])
print("Every second element:", arr_1d_slice[::2])
print("Reverse array:", arr_1d_slice[::-1])

1D Array for Slicing: [1 2 3 4 5 6 7 8]
Elements from index 2 to 5 (exclusive): [3 4 5]
Every second element: [1 3 5 7]
Reverse array: [8 7 6 5 4 3 2 1]


## Slicing 2D NumPy Arrays (More Examples)

In [31]:
arr_2d_slice = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("2D Array for Slicing:\n", arr_2d_slice)
print("First two rows, all columns:\n", arr_2d_slice[:2, :])
print("All rows, last two columns:\n", arr_2d_slice[:, 2:])
print("Middle sub-matrix (row 0-1, col 1-2):\n", arr_2d_slice[0:2, 1:3])

2D Array for Slicing:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
First two rows, all columns:
 [[1 2 3 4]
 [5 6 7 8]]
All rows, last two columns:
 [[ 3  4]
 [ 7  8]
 [11 12]]
Middle sub-matrix (row 0-1, col 1-2):
 [[2 3]
 [6 7]]


## Reshaping 1D NumPy Arrays (More Examples)

In [32]:
arr_1d_reshape = np.arange(12)
print("Original 1D array:", arr_1d_reshape)

reshaped_3x4 = arr_1d_reshape.reshape(3, 4)
print("Reshaped to 3x4:\n", reshaped_3x4)

reshaped_2x6 = arr_1d_reshape.reshape(2, -1) # -1 infers column count
print("Reshaped to 2 rows (inferred cols):\n", reshaped_2x6)

Original 1D array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped to 3x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Reshaped to 2 rows (inferred cols):
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


## Reshaping 2D NumPy Arrays (More Examples)

In [33]:
arr_2d_reshape = np.array([[1, 2, 3], [4, 5, 6]])
print("Original 2D array:\n", arr_2d_reshape)

flat_arr = arr_2d_reshape.flatten()
print("Flattened 1D array (copy):", flat_arr)

raveled_arr = arr_2d_reshape.ravel()
print("Raveled 1D array (view or copy):", raveled_arr)

Original 2D array:
 [[1 2 3]
 [4 5 6]]
Flattened 1D array (copy): [1 2 3 4 5 6]
Raveled 1D array (view or copy): [1 2 3 4 5 6]


## Joining 1D NumPy Arrays (More Examples)

In [34]:
arr_j1 = np.array([1, 2])
arr_j2 = np.array([3, 4])
arr_j3 = np.array([5, 6])

# Concatenate 1D arrays
joined_1d = np.concatenate((arr_j1, arr_j2, arr_j3))
print("Concatenated 1D arrays:", joined_1d)

Concatenated 1D arrays: [1 2 3 4 5 6]


## Joining 2D NumPy Arrays (More Examples)

In [35]:
arr_j2d_a = np.array([[10, 20], [30, 40]])
arr_j2d_b = np.array([[50, 60]]) # Note different shape for vstack

# Vertical stack (rows added)
joined_v_2d = np.vstack((arr_j2d_a, arr_j2d_b))
print("Vertically stacked 2D arrays:\n", joined_v_2d)

arr_j2d_c = np.array([[7, 8]]) # Reshape for hstack
arr_j2d_d = np.array([[9], [10]])

# Horizontal stack (columns added - requires matching rows)
# For simplicity, will use concatenate here as hstack requires matching rows for different 2d arrays
joined_h_2d_concat = np.concatenate((arr_j2d_a, np.array([[1,2],[3,4]])), axis=1) # Example with same row count
print("Horizontally concatenated 2D arrays:\n", joined_h_2d_concat)

Vertically stacked 2D arrays:
 [[10 20]
 [30 40]
 [50 60]]
Horizontally concatenated 2D arrays:
 [[10 20  1  2]
 [30 40  3  4]]


## Splitting 1D NumPy Arrays (More Examples)

In [36]:
arr_1d_split = np.arange(1, 11)
print("1D Array for Splitting:", arr_1d_split)

# Split into N equally sized arrays
parts_equal = np.split(arr_1d_split, 2) # Split into 2 arrays
print("Split into 2 equal parts:", parts_equal)

# Split at specific indices
parts_indices = np.split(arr_1d_split, [3, 7]) # Split before index 3, and before index 7
print("Split at indices 3 and 7:", parts_indices)

1D Array for Splitting: [ 1  2  3  4  5  6  7  8  9 10]
Split into 2 equal parts: [array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]
Split at indices 3 and 7: [array([1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10])]


## Splitting 2D NumPy Arrays (More Examples)

In [37]:
arr_2d_split = np.arange(16).reshape(4, 4)
print("2D Array for Splitting:\n", arr_2d_split)

# Vertical split (by rows)
split_rows_2d = np.vsplit(arr_2d_split, 2)
print("Vertical split into 2 parts:\n", split_rows_2d)

# Horizontal split (by columns)
split_cols_2d = np.hsplit(arr_2d_split, 2)
print("Horizontal split into 2 parts:\n", split_cols_2d)

2D Array for Splitting:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Vertical split into 2 parts:
 [array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
Horizontal split into 2 parts:
 [array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


## More Simple Splitting Examples: 1D Arrays

In [38]:
arr_1d_split_simple = np.arange(6)
print("Original 1D array:", arr_1d_split_simple)

# Split into two equal parts
part1_1d, part2_1d = np.split(arr_1d_split_simple, 2)
print("Split into 2 equal parts:", part1_1d, part2_1d)

# Split at a specific index
first_half, second_half = np.split(arr_1d_split_simple, [3]) # Split before index 3
print("Split at index 3:", first_half, second_half)

Original 1D array: [0 1 2 3 4 5]
Split into 2 equal parts: [0 1 2] [3 4 5]
Split at index 3: [0 1 2] [3 4 5]


## More Simple Splitting Examples: 2D Arrays

In [39]:
arr_2d_split_simple = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print("Original 2D array:\n", arr_2d_split_simple)

# Split horizontally (by columns) into two equal parts
left_half_2d, right_half_2d = np.hsplit(arr_2d_split_simple, 2)
print("\nHorizontal split (2 parts):\n", left_half_2d, "\n", right_half_2d)

# Split vertically (by rows) - requires at least 2 rows
arr_2d_split_rows = np.array([[10, 11], [12, 13], [14, 15], [16, 17]])
print("\nOriginal 2D array for vertical split:\n", arr_2d_split_rows)
upper_half_2d, lower_half_2d = np.vsplit(arr_2d_split_rows, 2)
print("\nVertical split (2 parts):\n", upper_half_2d, "\n", lower_half_2d)

Original 2D array:
 [[1 2 3 4]
 [5 6 7 8]]

Horizontal split (2 parts):
 [[1 2]
 [5 6]] 
 [[3 4]
 [7 8]]

Original 2D array for vertical split:
 [[10 11]
 [12 13]
 [14 15]
 [16 17]]

Vertical split (2 parts):
 [[10 11]
 [12 13]] 
 [[14 15]
 [16 17]]


## Indexing NumPy Arrays

In [18]:
# Indexing
print("Element at (0, 0):", base_arr[0, 0])
print("Element at row 1, col 2:", base_arr[1, 2])
print("First row:", base_arr[0])
print("First column:", base_arr[:, 0])

Element at (0, 0): 1
Element at row 1, col 2: 6
First row: [1 2 3]
First column: [1 4 7]


## Slicing NumPy Arrays

In [19]:
# Slicing
sub_array = base_arr[:2, 1:3]
print("\nSliced Sub-array (first 2 rows, columns 1-2):\n", sub_array)

# Modify a slice (this will change the original array)
sub_array_copy = base_arr[:2, 1:3].copy() # Use .copy() to avoid modifying original
sub_array_copy[0, 0] = 99
print("\nOriginal Array after modifying a copy of slice (no change):\n", base_arr)
print("Modified Slice Copy:\n", sub_array_copy)


Sliced Sub-array (first 2 rows, columns 1-2):
 [[2 3]
 [5 6]]

Original Array after modifying a copy of slice (no change):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Modified Slice Copy:
 [[99  3]
 [ 5  6]]


## Reshaping NumPy Arrays

In [20]:
# Reshaping
reshaped_1d = base_arr.reshape(9)
print("\nReshaped to 1D array:\n", reshaped_1d)

reshaped_col = base_arr.reshape(-1, 1) # -1 infers the size
print("\nReshaped to single column array:\n", reshaped_col)

# Using .flatten() or .ravel()
flattened_arr = base_arr.flatten()
print("\nFlattened array (copy):\n", flattened_arr)
raveled_arr = base_arr.ravel()
print("\nRaveled array (view or copy):\n", raveled_arr)


Reshaped to 1D array:
 [1 2 3 4 5 6 7 8 9]

Reshaped to single column array:
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]

Flattened array (copy):
 [1 2 3 4 5 6 7 8 9]

Raveled array (view or copy):
 [1 2 3 4 5 6 7 8 9]


## Joining NumPy Arrays

In [21]:
# Joining (Concatenation)
arr_a = np.array([[1, 2], [3, 4]])
arr_b = np.array([[5, 6], [7, 8]])

joined_v = np.vstack((arr_a, arr_b))
print("\nVertically stacked (np.vstack):\n", joined_v)

joined_h = np.hstack((arr_a, arr_b))
print("\nHorizontally stacked (np.hstack):\n", joined_h)

# Using np.concatenate
joined_concat_v = np.concatenate((arr_a, arr_b), axis=0)
print("\nConcatenated vertically (np.concatenate, axis=0):\n", joined_concat_v)

joined_concat_h = np.concatenate((arr_a, arr_b), axis=1)
print("\nConcatenated horizontally (np.concatenate, axis=1):\n", joined_concat_h)


Vertically stacked (np.vstack):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontally stacked (np.hstack):
 [[1 2 5 6]
 [3 4 7 8]]

Concatenated vertically (np.concatenate, axis=0):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Concatenated horizontally (np.concatenate, axis=1):
 [[1 2 5 6]
 [3 4 7 8]]


## Splitting NumPy Arrays

In [22]:
# Splitting
large_arr = np.arange(1, 17).reshape(4, 4)
print("\nLarge array for splitting:\n", large_arr)

split_v1, split_v2 = np.vsplit(large_arr, 2)
print("\nVertically split array 1 (np.vsplit):\n", split_v1)
print("\nVertically split array 2 (np.vsplit):\n", split_v2)

split_h1, split_h2 = np.hsplit(large_arr, 2)
print("\nHorizontally split array 1 (np.hsplit):\n", split_h1)
print("\nHorizontally split array 2 (np.hsplit):\n", split_h2)

# Using np.array_split (more flexible for unequal splits)
arr_to_split = np.array([10, 20, 30, 40, 50, 60, 70])
splits = np.array_split(arr_to_split, 3) # Split into 3 arrays
print("\nArray split into 3 parts (np.array_split):\n", splits)


Large array for splitting:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Vertically split array 1 (np.vsplit):
 [[1 2 3 4]
 [5 6 7 8]]

Vertically split array 2 (np.vsplit):
 [[ 9 10 11 12]
 [13 14 15 16]]

Horizontally split array 1 (np.hsplit):
 [[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]

Horizontally split array 2 (np.hsplit):
 [[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]

Array split into 3 parts (np.array_split):
 [array([10, 20, 30]), array([40, 50]), array([60, 70])]
